AllCops:
  Exclude:
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/initializers/*'
    - 'log/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false