
language: ruby
# Use travis CI Docker Infrastructure
sudo: false
cache: bundler
notifications:
  email: false
  slack:
    rooms:
      secure: BU22IQqojSJwkLBpLF4y2+BgEPUaZ7cdxRExsdWqDCoXGKSVBFY1I0/E4qm+abPZzSUqfvx8CC2hRqvdtymAmHbew6L8K+yDfdmBKwug3WRXWBqy65xWdQBQlvnYhmn7WfstbVYb2xHQj3YE+ZtNPI0UmJRUYdAJLI2qlzOjes8=
    on_success: change
    on_failure: always
services:
  - postgresql
before_script:
  - psql -c 'create database scoreboard_test;' -U postgres
script:
- bundle exec brakeman -qAzw1
- bundle exec bundle-audit check --update
- bundle exec rake test
- bundle exec rubocop